# Generated by Django 3.2.12 on 2022-03-23 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20220317_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetlike',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.tweetlike'),
        ),
    ]
