# Generated by Django 3.2.12 on 2022-03-23 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweetlike_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetlike',
            name='parent',
        ),
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.tweet'),
        ),
    ]
